# https://docs.gradle.org/current/userguide/version_catalogs.html#sec:version-catalog-declaration
[versions]
assertj-vavr = "0.4.3"
spring-boot = "3.5.6"
vavr = "0.10.7"
version-catalog-update = "1.0.1"

[libraries]
assertj-vavr = { module = "org.assertj:assertj-vavr", version.ref = "assertj-vavr" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
